MainContainer:


<MainContainer>:
    CustomDropDown:
        # size_hint: 0.5, 0.5
        # pos_hint: {"center_x": .5, "center_y": .5}
    # MDDropDownItem:
    #     pos_hint: {'center_x': .5, 'center_y': .6}
    #     size_hint_x: None
    #     width: "200dp"
    #     text: "Open Menu"
        # on_release: root.menu.open()


<CustomDropDown>:
    field: field
    MDDropDownItem:
        id: field
        # # pos_hint: {'center_x': .5, 'center_y': .5}
        # size_hint_x: None
        # width: "200dp"
        text: "Open Menu"
        on_release: root.parent.menu.open()