MainContainer:


<MainContainer>:
    information_overlay: information_overlay
    BoxLayout:
        orientation: "vertical"
        padding: "15dp", "15dp"
        spacing: "10dp"
        Label:
            text: "PasswordChecker"
            font_size: "40dp"
            size_hint: 1, 3
        TextInput:
            id: password_input
            font_size: "30dp"
            size_hint: 0.5, 1
            pos_hint: {"center_x": 0.5}
            padding: "20dp", "20dp"
        Label:
            text: root.status_text
        Button:
            text: "Check"
            size_hint: 0.3, 1
            pos_hint: {"center_x": 0.5}
            on_release: root.handle_check_button_press(password_input.text)
        Button:
            text: "Info"
            size_hint: 0.3, 0.5
            pos_hint: {"center_x": 0.5}
            on_release: root.handle_info_button_press()
    InformationOverlay:
        id: information_overlay
        orientation: "vertical"
        padding: "15dp", "15dp"
        spacing: "10dp"
        opacity: 0
        canvas:
            Color:
                rgb: 0, 0, 0
            Rectangle:
                size: root.size
        Label:
            text: "Information"
            font_size: "30dp"
        Label:
            text: root.information_text
            font_size: "20dp"
            size_hint: 1, 3
        Button:
            text: "Back"
            size_hint: 0.2, 0.5
            pos_hint: {"center_x": 0.5}
            on_release: self.parent.handle_info_back_button_press()
